/**
 * GTMXpert Export Utilities
 * Provides Markdown and HTML export options
 */

export function exportToMarkdown(events, clientName) {
    let md = `# Tracking Plan: ${clientName}\n`;
    md += `Generated by GTMXpert (ESES Agency) · ${new Date().toLocaleDateString()}\n\n`;

    events.forEach((event, index) => {
        md += `## ${index + 1}. ${event.event_name}\n`;
        md += `**Page context:** ${event.page || 'Home / All Pages'}\n\n`;

        md += `### Strategic Rationale\n`;
        md += `${event.documentation?.rationale || event.rationale || 'N/A'}\n\n`;

        md += `### Implementation Details\n`;
        md += `**Capture Strategy:** ${event.analysis?.capture_strategy || 'N/A'}\n\n`;

        if (event.variables?.length > 0) {
            md += `#### Variables\n`;
            event.variables.forEach(v => {
                md += `- **${v.name || 'N/A'}** (${v.type || 'N/A'})\n`;
                md += `  \`\`\`javascript\n${v.code || '// Empty'}\n  \`\`\`\n`;
                md += `  Returns: \`${v.returns || 'N/A'}\`\n\n`;
            });
        }

        md += `#### Trigger\n`;
        md += `- **Name:** ${event.trigger?.name || 'N/A'}\n`;
        md += `- **Type:** ${event.trigger?.type || 'N/A'}\n`;
        md += `- **Conditions:**\n`;
        (event.trigger?.conditions || []).forEach(c => {
            md += `  - ${c.field || 'Field'} ${c.operator || ''} ${c.value || ''}\n`;
        });
        if (event.trigger?.notes) md += `  - *Notes:* ${event.trigger.notes}\n`;
        md += `\n`;

        if (event.tags?.length > 0) {
            md += `#### Tags\n`;
            event.tags.forEach(t => {
                md += `- **${t.name || 'N/A'}** [${t.platform || 'N/A'}]\n`;
                const tParams = t.parameters || t.object_properties || [];
                if (tParams.length > 0) {
                    md += `  | Parameter | Value |\n  |---|---|\n`;
                    tParams.forEach(p => {
                        md += `  | ${p.key || ''} | ${p.value || ''} |\n`;
                    });
                }
                if (t.justification) md += `  - *Justification:* ${t.justification}\n`;
                md += `\n`;
            });
        }

        md += `#### Validation Checklist\n`;
        const checklist = event.documentation?.checklist || event.checklist || [];
        checklist.forEach(item => {
            md += `- [ ] ${item}\n`;
        });
        md += `\n---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Tracking_Plan_${clientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
}

export function exportToHTML(events, clientName) {
    let html = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Tracking Plan: ${clientName}</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1B1B1A; max-width: 900px; margin: 0 auto; padding: 60px 40px; background: #F8F8F8; }
            .card { background: white; border: 1px solid #E5E5E5; border-radius: 16px; padding: 40px; margin-bottom: 40px; box-shadow: 0 4px 20px rgba(0,0,0,0.03); }
            header { margin-bottom: 60px; border-bottom: 3px solid #82FF7A; padding-bottom: 20px; }
            h1 { font-size: 32px; font-weight: 900; margin: 0; color: #1B1B1A; }
            h2 { font-size: 24px; font-weight: 900; color: #1B1B1A; margin-top: 0; border-left: 5px solid #82FF7A; padding-left: 15px; }
            h3 { font-size: 14px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.1em; color: #888; margin-top: 30px; margin-bottom: 10px; }
            h4 { font-size: 16px; font-weight: 700; margin-bottom: 10px; }
            .rationale { background: #F0FFF0; padding: 20px; border-radius: 12px; font-style: italic; border: 1px solid #D1F2D1; margin: 20px 0; }
            .strategy { background: #F0F7FF; padding: 15px; border-radius: 8px; border-left: 4px solid #0070F3; margin-bottom: 25px; font-size: 14px; }
            pre { background: #1B1B1A; color: #82FF7A; padding: 20px; border-radius: 12px; overflow-x: auto; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 13px; line-height: 1.5; }
            table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 14px; }
            th, td { border-bottom: 1px solid #EEE; padding: 12px 15px; text-align: left; }
            th { background-color: #FAFAFA; color: #666; font-weight: 700; }
            .tag-badge { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: 800; margin-right: 8px; text-transform: uppercase; }
            .ga4 { background: #FFEDD5; color: #EA580C; }
            .facebook { background: #DBEAFE; color: #2563EB; }
            .checklist-item { display: flex; align-items: flex-start; gap: 10px; margin-bottom: 8px; font-size: 14px; }
            .checkbox { width: 16px; height: 16px; border: 2px solid #82FF7A; border-radius: 4px; flex-shrink: 0; margin-top: 3px; }
            .footer { text-align: center; font-size: 12px; color: #AAA; margin-top: 80px; }
        </style>
    </head>
    <body>
        <header>
            <h1>GTMXpert · ${clientName}</h1>
            <p><strong>Tracking Plan Implementation Guide</strong> · ${new Date().toLocaleDateString()}</p>
        </header>
    `;

    events.forEach((event, index) => {
        html += `
        <div class="card">
            <h2>${index + 1}. ${event.event_name || 'Event'}</h2>
            <p><small>Página: <code>${event.page || 'Home / Global'}</code></small></p>
            
            <div class="rationale">
                <strong>Justificación Estratégica:</strong><br>
                ${event.documentation?.rationale || event.rationale || 'N/A'}
            </div>

            <div class="strategy">
                <strong>Estrategia de Captura:</strong><br>
                ${event.analysis?.capture_strategy || 'N/A'}
            </div>

            <div class="section">
                <h3>Variables JavaScript</h3>
                ${(event.variables || []).map(v => `
                    <div style="margin-bottom: 20px;">
                        <strong>${v.name || 'N/A'}</strong> <span style="color:#888; font-size: 12px;">(${v.type || 'N/A'})</span>
                        <pre><code>${v.code || '// Empty'}</code></pre>
                        <p style="font-size: 12px; color: #666;">Devuelve: <code>${v.returns || 'N/A'}</code></p>
                    </div>
                `).join('')}
            </div>

            <div class="section">
                <h3>Trigger: ${event.trigger?.name || 'N/A'}</h3>
                <p style="font-size: 14px; margin-bottom: 5px;">Tipo: <code>${event.trigger?.type || 'N/A'}</code></p>
                <table>
                    <tr><th>Campo</th><th>Operador</th><th>Valor</th></tr>
                    ${(event.trigger?.conditions || []).map(c => `<tr><td>${c.field || ''}</td><td>${c.operator || ''}</td><td><code>${c.value || ''}</code></td></tr>`).join('')}
                </table>
                ${event.trigger?.notes ? `<p style="font-size: 12px; color: #888; font-style: italic;">Nota: ${event.trigger.notes}</p>` : ''}
            </div>

            <div class="section">
                <h3>Etiquetas y Píxeles</h3>
                ${(event.tags || []).map(t => {
                    const tParams = t.parameters || t.object_properties || [];
                    return `
                    <div style="margin-bottom: 25px; border-bottom: 1px dashed #EEE; padding-bottom: 15px;">
                        <span class="tag-badge ${(t.platform || '').toLowerCase()}">${t.platform || ''}</span>
                        <strong>${t.name || ''}</strong>
                        ${tParams.length > 0 ? `
                        <table>
                            <tr><th style="width: 40%;">Parámetro</th><th>Valor</th></tr>
                            ${tParams.map(p => `<tr><td>${p.key || ''}</td><td><code>${p.value || ''}</code></td></tr>`).join('')}
                        </table>` : '<p><small>Sin parámetros específicos.</small></p>'}
                        ${t.justification ? `<p style="font-size: 12px; color: #777; background: #FAFAFA; padding: 10px; border-radius: 6px;">${t.justification}</p>` : ''}
                    </div>
                    `;
                }).join('')}
            </div>

            <div class="section">
                <h3>Checklist de Validación</h3>
                <div style="margin-top: 15px;">
                    ${(event.documentation?.checklist || event.checklist || []).map(item => `
                        <div class="checklist-item">
                            <div class="checkbox"></div>
                            <div>${item}</div>
                        </div>
                    `).join('')}
                </div>
            </div>
        </div>
        `;
    });

    html += `
        <div class="footer">
            Generado por GTMXpert (ESES Agency) · Standard v1.0
        </div>
    </body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Tracking_Plan_${clientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.html`;
    a.click();
}
