/**
 * GTMXpert Export Utilities
 * Provides Markdown and HTML export options
 */

export function exportToMarkdown(events, clientName) {
    let md = `# Tracking Plan: ${clientName}\n`;
    md += `Generated by GTMXpert (ESES Agency) · ${new Date().toLocaleDateString()}\n\n`;

    events.forEach((event, index) => {
        md += `## ${index + 1}. ${event.event_name}\n`;
        md += `**Page context:** ${event.page || 'Home / All Pages'}\n\n`;

        md += `### Strategic Rationale\n`;
        md += `${event.documentation?.rationale || event.rationale || 'N/A'}\n\n`;

        md += `### Implementation Details\n`;
        md += `**Capture Strategy:** ${event.analysis?.capture_strategy || 'N/A'}\n\n`;

        if (event.variables?.length > 0) {
            md += `#### Variables\n`;
            event.variables.forEach(v => {
                md += `- **${v.name || 'N/A'}** (${v.type || 'N/A'})\n`;
                md += `  \`\`\`javascript\n${v.code || '// Empty'}\n  \`\`\`\n`;
                md += `  Returns: \`${v.returns || 'N/A'}\`\n\n`;
            });
        }

        md += `#### Trigger\n`;
        md += `- **Name:** ${event.trigger?.name || 'N/A'}\n`;
        md += `- **Type:** ${event.trigger?.type || 'N/A'}\n`;
        md += `- **Conditions:**\n`;
        (event.trigger?.conditions || []).forEach(c => {
            md += `  - ${c.field || 'Field'} ${c.operator || ''} ${c.value || ''}\n`;
        });
        if (event.trigger?.notes) md += `  - *Notes:* ${event.trigger.notes}\n`;
        md += `\n`;

        if (event.tags?.length > 0) {
            md += `#### Tags\n`;
            event.tags.forEach(t => {
                md += `- **${t.name || 'N/A'}** [${t.platform || 'N/A'}]\n`;
                const tParams = t.parameters || t.object_properties || [];
                if (tParams.length > 0) {
                    md += `  | Parameter | Value |\n  |---|---|\n`;
                    tParams.forEach(p => {
                        md += `  | ${p.key || ''} | ${p.value || ''} |\n`;
                    });
                }
                if (t.justification) md += `  - *Justification:* ${t.justification}\n`;
                md += `\n`;
            });
        }

        md += `#### Validation Checklist\n`;
        const checklist = event.documentation?.checklist || event.checklist || [];
        checklist.forEach(item => {
            md += `- [ ] ${item}\n`;
        });
        md += `\n---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Tracking_Plan_${clientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
}

export function exportToHTML(events, clientName) {
    const today = new Date().toLocaleDateString('es-ES', { day: '2-digit', month: 'long', year: 'numeric' });
    let html = `
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>Plan de Tracking: ${clientName}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Work+Sans:wght@700;800;900&display=swap" rel="stylesheet">
        <style>
            :root {
                --brand-green: #82FF7A;
                --brand-dark: #1B1B1A;
                --brand-gray: #F8F8F8;
                --text-main: #1B1B1A;
                --text-muted: #666666;
                --border-color: #EEEEEE;
            }
            
            * { box-sizing: border-box; }
            body { 
                font-family: 'Inter', -apple-system, sans-serif; 
                line-height: 1.6; 
                color: var(--text-main); 
                max-width: 1000px; 
                margin: 0 auto; 
                padding: 80px 40px; 
                background: var(--brand-gray); 
            }
            
            header { 
                margin-bottom: 80px; 
                border-bottom: 4px solid var(--brand-green); 
                padding-bottom: 40px; 
            }
            
            h1 { 
                font-family: 'Work Sans', sans-serif; 
                font-size: 48px; 
                font-weight: 900; 
                margin: 0; 
                letter-spacing: -0.02em;
                line-height: 1.1;
                color: var(--brand-dark);
            }
            
            .subtitle {
                font-size: 18px;
                color: var(--text-muted);
                margin-top: 10px;
                font-weight: 500;
            }

            .card { 
                background: white; 
                border: 1px solid var(--border-color); 
                border-radius: 24px; 
                padding: 60px; 
                margin-bottom: 60px; 
                box-shadow: 0 10px 40px rgba(0,0,0,0.02); 
                position: relative;
                overflow: hidden;
            }

            .card::before {
                content: "";
                position: absolute;
                top: 0; left: 0; width: 100%; height: 8px;
                background: var(--brand-green);
                opacity: 0.3;
            }
            
            h2 { 
                font-family: 'Work Sans', sans-serif;
                font-size: 28px; 
                font-weight: 800; 
                color: var(--brand-dark); 
                margin-top: 0; 
                margin-bottom: 25px;
                display: flex;
                align-items: center;
                gap: 15px;
            }

            .event-number {
                background: var(--brand-dark);
                color: var(--brand-green);
                width: 40px; height: 40px;
                display: flex; align-items: center; justify-content: center;
                border-radius: 50%;
                font-size: 18px;
                font-weight: 900;
            }
            
            .page-path {
                display: inline-block;
                background: var(--brand-gray);
                padding: 6px 12px;
                border-radius: 8px;
                font-family: monospace;
                font-size: 13px;
                margin-bottom: 30px;
            }

            h3 { 
                font-family: 'Work Sans', sans-serif;
                font-size: 13px; 
                font-weight: 800; 
                text-transform: uppercase; 
                letter-spacing: 0.15em; 
                color: var(--text-muted); 
                margin-top: 45px; 
                margin-bottom: 15px;
                border-bottom: 1px solid var(--border-color);
                padding-bottom: 8px;
            }

            .rationale { 
                background: #F0FFF0; 
                padding: 30px; 
                border-radius: 16px; 
                border-left: 6px solid var(--brand-green); 
                margin: 30px 0;
            }
            
            .strategy { 
                background: #F0F7FF; 
                padding: 20px; 
                border-radius: 12px; 
                border-left: 6px solid #0070F3; 
                margin-bottom: 30px; 
                font-size: 15px; 
            }

            pre { 
                background: var(--brand-dark); 
                color: var(--brand-green); 
                padding: 25px; 
                border-radius: 16px; 
                overflow-x: auto; 
                font-family: "SFMono-Regular", Consolas, monospace; 
                font-size: 14px; 
                line-height: 1.6; 
                margin: 15px 0;
            }

            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { border-bottom: 1px solid var(--border-color); padding: 16px 20px; text-align: left; }
            th { background-color: var(--brand-gray); color: var(--text-muted); font-weight: 700; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
            
            .tag-badge { 
                display: inline-block; 
                padding: 4px 12px; 
                border-radius: 6px; 
                font-size: 11px; 
                font-weight: 800; 
                margin-right: 10px; 
                text-transform: uppercase; 
                letter-spacing: 0.05em;
            }
            .ga4 { background: #FFEDD5; color: #EA580C; }
            .facebook { background: #DBEAFE; color: #2563EB; }
            
            .checklist-item { display: flex; align-items: flex-start; gap: 15px; margin-bottom: 12px; font-size: 15px; }
            .checkbox { width: 20px; height: 20px; border: 2px solid var(--brand-green); border-radius: 6px; flex-shrink: 0; margin-top: 2px; }
            
            .footer { 
                text-align: center; 
                font-size: 13px; 
                color: var(--text-muted); 
                margin-top: 100px; 
                padding-top: 40px;
                border-top: 1px solid var(--border-color);
            }

            @media print {
                body { padding: 0; background: white; }
                .card { box-shadow: none; border: 1px solid #eee; break-inside: avoid; }
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Guía de Etiquetado GTM</h1>
            <div class="subtitle">${clientName} · ${today}</div>
        </header>
    `;

    events.forEach((event, index) => {
        html += `
        <div class="card">
            <h2>
                <div class="event-number">${index + 1}</div>
                ${event.event_name || 'Evento'}
            </h2>
            <div class="page-path">Contexto: ${event.page || 'Global'}</div>
            
            <div class="rationale">
                <strong style="display:block; margin-bottom:8px; font-family:'Work Sans'; text-transform:uppercase; font-size:12px; letter-spacing:0.1em;">Justificación Estratégica</strong>
                ${event.documentation?.rationale || event.rationale || 'N/A'}
            </div>

            <div class="strategy">
                <strong style="display:block; margin-bottom:5px;">Estrategia de Captura:</strong>
                ${event.analysis?.capture_strategy || 'N/A'}
            </div>

            <section>
                <h3>1. Variables JavaScript</h3>
                ${(event.variables || []).map(v => `
                    <div style="margin-bottom: 30px;">
                        <div style="display:flex; justify-content:space-between; align-items:baseline; margin-bottom:10px;">
                            <strong style="color:var(--brand-dark); font-size:16px;">${v.name || 'N/A'}</strong>
                            <span style="color:var(--text-muted); font-size: 12px; font-weight:600;">[${v.type || 'N/A'}]</span>
                        </div>
                        <pre><code>${v.code || '// Sin código'}</code></pre>
                        <div style="font-size: 13px; color: var(--text-muted); font-style:italic;">
                            &rarr; Devuelve: <code style="color:var(--brand-dark); font-weight:700;">${v.returns || 'N/A'}</code>
                        </div>
                    </div>
                `).join('')}
            </section>

            <section>
                <h3>2. Trigger: ${event.trigger?.name || 'N/A'}</h3>
                <p style="font-size: 14px; margin-bottom: 10px;">Tipo: <strong>${event.trigger?.type || 'N/A'}</strong></p>
                <table>
                    <thead>
                        <tr><th>Campo</th><th>Operador</th><th>Valor</th></tr>
                    </thead>
                    <tbody>
                        ${(event.trigger?.conditions || []).map(c => `<tr><td>${c.field || ''}</td><td>${c.operator || ''}</td><td><code>${c.value || ''}</code></td></tr>`).join('')}
                    </tbody>
                </table>
                ${event.trigger?.notes ? `<p style="font-size: 13px; color: var(--text-muted); font-style: italic; background:#fcfcfc; padding:10px; border-radius:8px;">${event.trigger.notes}</p>` : ''}
            </section>

            <section>
                <h3>3. Etiquetas y Píxeles</h3>
                ${(event.tags || []).map(t => {
                    const tParams = t.parameters || t.object_properties || [];
                    const platformClass = (t.platform || '').toLowerCase();
                    return `
                    <div style="margin-bottom: 40px; border-bottom: 1px dashed var(--border-color); padding-bottom: 30px; last-child:border-0;">
                        <div style="margin-bottom:15px;">
                            <span class="tag-badge ${platformClass}">${t.platform || ''}</span>
                            <strong style="font-family:'Work Sans'; font-size:18px;">${t.name || ''}</strong>
                        </div>
                        ${tParams.length > 0 ? `
                        <table>
                            <thead>
                                <tr><th style="width: 35%;">Parámetro / Propiedad</th><th>Valor / Variable GTM</th></tr>
                            </thead>
                            <tbody>
                                ${tParams.map(p => `<tr><td>${p.key || ''}</td><td><code>${p.value || ''}</code></td></tr>`).join('')}
                            </tbody>
                        </table>` : '<p style="font-size:13px; color:var(--text-muted);">Sin parámetros específicos.</p>'}
                        ${t.justification ? `<div style="font-size: 13px; color: #555; background: var(--brand-gray); padding: 15px; border-radius: 10px; margin-top:15px;">
                            <strong>Justificación:</strong> ${t.justification}
                        </div>` : ''}
                    </div>
                    `;
                }).join('')}
            </section>

            <section>
                <h3>4. Checklist de Validación</h3>
                <div style="margin-top: 20px;">
                    ${(event.documentation?.checklist || event.checklist || []).map(item => `
                        <div class="checklist-item">
                            <div class="checkbox"></div>
                            <div>${item}</div>
                        </div>
                    `).join('')}
                </div>
            </section>
        </div>
        `;
    });

    html += `
        <div class="footer">
            Generado por <strong>GTMXpert</strong> &middot; ESES Agency &middot; Motor Estándar v1.0<br>
            <span style="font-size:11px; opacity:0.7; margin-top:10px; display:block;">&copy; ${new Date().getFullYear()} Documento estratégico confidencial para ${clientName}</span>
        </div>
    </body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GTMXpert_Plan_${clientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.html`;
    a.click();
}
